# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SephoraTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SephoraTest
  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RxGesture'
  pod 'RxDataSources'
 
  target 'SephoraTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SephoraTestUITests' do
    # Pods for testing
  end

end
